ALTER TABLE [dbo].[TeacherFaculties]
    ADD CONSTRAINT [PK_TeacherFaculties] PRIMARY KEY CLUSTERED ([TeacherID] ASC, [FacultyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

